services:
  licensing_db:
    image: postgres:18-alpine
    ports:
      - "15433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ostock_dev
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./compose/:/docker-entrypoint-initdb.d/
