spring.application.name=licensing-service
management.endpoint.health.show-details=always
spring.profiles.active=dev
# Circuitbreaker
resilience4j.circuitbreaker.configs.default.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.configs.default.sliding-window-size=3
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=3
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.slow-call-rate-threshold=50
resilience4j.circuitbreaker.configs.default.slow-call-duration-threshold=1s
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.licenseById.register-health-indicator=true
resilience4j.circuitbreaker.instances.licenseByClientType.register-health-indicator=true

resilience4j.bulkhead.instances.bulkheadLicenseByClientType.max-wait-duration=10ms
resilience4j.bulkhead.instances.bulkheadLicenseByClientType.max-concurrent-calls=10

resilience4j.thread-pool-bulkhead.instances.bulkheadLicenseByClientType.max-thread-pool-size=1
resilience4j.thread-pool-bulkhead.instances.bulkheadLicenseByClientType.core-thread-pool-size=1
resilience4j.thread-pool-bulkhead.instances.bulkheadLicenseByClientType.queue-capacity=1
resilience4j.thread-pool-bulkhead.instances.bulkheadLicenseByClientType.keep-alive-duration=20ms