## CDS support (experimental)
# Specify explicitly the dialect (here for PostgreSQL, adapt for your database)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable Hibernate usage of JDBC metadata
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# Database initialization should typically be performed outside of Spring lifecycle
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never

spring.datasource.hikari.allow-pool-suspension=true

spring.flyway.enabled=false

spring.datasource.url=jdbc:postgresql://cds
spring.datasource.username=cds
spring.datasource.password=cds