spring.config.import=optional:configserver:http://localhost:8071
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.enabled=false
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
logging.config=classpath:logback-logstash-spring.xml
logging.logstash.host=localhost
logging.logstash.port=5000