CREATE TABLE IF NOT EXISTS public.license
(
    license_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    description     text,
    product_name    text   NOT NULL,
    license_type    text   NOT NULL,
    comment         text,
    CONSTRAINT licenses_pkey PRIMARY KEY (license_id)
);

ALTER TABLE public.license
    OWNER to postgres;