CREATE TABLE IF NOT EXISTS public.organization
(
    organization_id bigint GENERATED BY DEFAULT AS IDENTITY,
    name            text,
    contact_name    text,
    contact_email   text,
    contact_phone   text,
    CONSTRAINT organizations_pkey PRIMARY KEY (organization_id)
);

ALTER TABLE public.organization
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.license
(
    license_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    description     text,
    product_name    text   NOT NULL,
    license_type    text   NOT NULL,
    comment         text,
    CONSTRAINT licenses_pkey PRIMARY KEY (license_id),
    CONSTRAINT licenses_organization_id_fkey FOREIGN KEY (organization_id)
        REFERENCES public.organization (organization_id)
);

ALTER TABLE public.license
    OWNER to postgres;